// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(RecipesContext))]
    partial class RecipesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Author = "Paul Sparks",
                            Date = new DateOnly(2024, 11, 8),
                            Description = "In a large wok, melt a spoonful of ghee and add thinly chopped chicken thigh. Once cooked, add 2 large eggs. After those are finished, add refrigerated white rice. Then, in order, add soy sauce, fish sauce, and gochujang. Make a hole in the center, add some more ghee, and fry up some minced garlic, sliced serrano peppers, and sliced shallots. Mix and cook for a short time, then incorporate into rice. Add dark soy sauce and shaoxing cooking wine. Turn off heat, then add MSG, sesame oil, and furikake rice seasoning. Mix well, and serve with sliced green onions on top.",
                            Name = "Chicken Fried Rice"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
